//! Generated types – do not edit by hand.
use serde_json::Value;

pub type CancelKeyDeletionRequest = Value;
pub type CreateKeyRequest = Value;
pub type DecryptDataKeyRequest = Value;
pub type DecryptDataKeyResponse = Value;
pub type DecryptRequest = Value;
pub type DecryptResponse = Value;
pub type DisableKeyRequest = Value;
pub type EnableKeyRequest = Value;
pub type EncryptRequest = Value;
pub type EncryptResponse = Value;
pub type EncryptionAlgorithm = Value;
pub type EncryptionContextMap = Value;
pub type GenerateDataKeyRequest = Value;
pub type GenerateDataKeyResponse = Value;
pub type KeyMetadataResponse = Value;
pub type KeySpec = Value;
pub type KeyState = Value;
pub type KeyTagsMap = Value;
pub type KeyUsage = Value;
pub type PurgeKeyRequest = Value;
pub type RotateKeyRequest = Value;
pub type ScheduleKeyDeletionRequest = Value;
pub type SignRequest = Value;
pub type SignResponse = Value;
pub type SigningAlgorithm = Value;
pub type VerifyRequest = Value;
pub type VerifyResponse = Value;
